### ISSUE TITLE
Bugs at implementation

### ISSUE THREAD

**Issue by omerday** [omerday/Doors-Task#52]
- [x] At door waiting beeps: 
```
Traceback (most recent call last):
  File ".\main.py", line 84, in <module>
    Df, miniDf, totalCoins = DoorPlay.run_task(window, params, 1, 0, Df, miniDf, io, ser)
  File "C:\Users\User\Documents\Doors-Task\Doors-Task-main\Assignments\Doors\DoorPlay.py", line 93, in run_task
    coinsWon, total_time, Df, miniDf, dict, lock = DoorPlayInfra.start_door(window, params, image, scenario[0], scenario[1],
  File "C:\Users\User\Documents\Doors-Task\Doors-Task-main\Assignments\Doors\DoorPlayInfra.py", line 299, in start_door
    play_sound("beep", 2, dict, Df)
  File "C:\Users\User\Documents\Doors-Task\Doors-Task-main\Assignments\Doors\DoorPlayInfra.py", line 460, in play_sound
    soundToPlay = sound.Sound(SOUNDS[soundType])
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\psychopy_sounddevice\backend_sounddevice.py", line 328, in __init__
    self.setSound(value, secs=self.secs, octave=self.octave,
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\psychopy_sounddevice\backend_sounddevice.py", line 392, in setSound
    raise err
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\psychopy_sounddevice\backend_sounddevice.py", line 382, in setSound
    label, s = streams.getStream(sampleRate=self.sampleRate,
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\psychopy_sounddevice\backend_sounddevice.py", line 97, in getStream
    return self._getStream(sampleRate,
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\psychopy_sounddevice\backend_sounddevice.py", line 135, in _getStream
    raise SoundFormatError(
psychopy.exceptions.SoundFormatError: Tried to create audio stream 48000_2_128 but 44100_2_128 already exists and win32 doesn't support multiple portaudio streams
```

- [x] At practice run:
```
Traceback (most recent call last):
  File ".\main.py", line 81, in <module>
    Df, miniDf = DoorPlay.practice_run(window, params, Df, miniDf, io, ser)
  File "C:\Users\User\Documents\Doors-Task\Doors-Task-main\Assignments\Doors\DoorPlay.py", line 33, in practice_run
    coinsWon, total_time, Df, miniDf, dict, lock = DoorPlayInfra.start_door(window, params, image, 0, 0,
  File "C:\Users\User\Documents\Doors-Task\Doors-Task-main\Assignments\Doors\DoorPlayInfra.py", line 259, in start_door
    Df = pandas.concat([Df, pandas.DataFrame.from_records([dict])])
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\pandas\core\reshape\concat.py", line 372, in concat
    op = _Concatenator(
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\pandas\core\reshape\concat.py", line 462, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'tuple'>'; only Series and DataFrame objs are valid
```

- [x] Remove "assignment ." import statements
- [x] Create Data folder
- [x] Change the dict names to be more indicative

**Comment by omerday** [comment]
The door's opening sound issue was due to an inconsistent sample rate. It should be similar for all sound files.
